<?php

class ReolinkCamera extends IPSModule {

    // overwrite default create function
    public function Create() {
        parent::Create();
        // TODO: Change the autogenerated stub
    }

    // called on changes
    public function ApplyChanges() {
        parent::ApplyChanges();
        // TODO: Change the autogenerated stub
    }

    public function RequestAction($Ident, $Value) {
        // TODO: change on var
    }

    /*------ generate form.json ------*/


}

?>